language: cpp

env:
  global:
    - GN_LNX64_SHA1: 3841819dc328973fb34ea2dd3bbbc0b63361b1f9

addons:
  apt:
    sources: &sources
      # this is needed for gcc and clang
      - ubuntu-toolchain-r-test
    packages: &packages
      - ninja-build

matrix:
  include:
    - compiler: gcc
      os: linux
      env: GN_ARGS='gcc_cc="gcc-4.9" gcc_cxx="g++-4.9" is_clang=false'
      addons: &gcc_addons
        apt:
          sources:
            - *sources
          packages:
            - g++-4.9
            - *packages

    - compiler: gcc
      os: linux
      env: GN_ARGS='gcc_cc="gcc-4.9" gcc_cxx="g++-4.9" is_clang=false is_debug=false'
      addons: *gcc_addons

    - compiler: gcc
      os: linux
      env: GN_ARGS='gcc_cc="gcc-4.9" gcc_cxx="g++-4.9" is_clang=false is_official_build=true'
      addons: *gcc_addons

    - compiler: clang
      os: linux
      env: GN_ARGS='clang_cc="clang-3.8" clang_cxx="clang++-3.8" is_clang=true'
      addons: &clang_addons
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - *sources
          packages:
            - clang-3.8
            - *packages

    - compiler: clang
      os: linux
      env: GN_ARGS='clang_cc="clang-3.8" clang_cxx="clang++-3.8" is_clang=true is_debug=false'
      addons: *clang_addons

    - compiler: clang
      os: linux
      env: GN_ARGS='clang_cc="clang-3.8" clang_cxx="clang++-3.8" is_clang=true is_official_build=true'
      addons: *clang_addons

script:
  - python gn_helpers_unittest.py
  - travis_retry wget --no-check-certificate --quiet -O gn https://storage.googleapis.com/chromium-gn/$GN_LNX64_SHA1
  - chmod +x gn
  - git clone --branch=testsrc https://github.com/dyu/gn-build.git testsrc
  - mkdir testsrc/gn-build
  - mv config testsrc/gn-build/
  - mv toolchain testsrc/gn-build/
  - chmod +x gn && ./gn gen gn-out --args="$GN_ARGS" --root=testsrc
  - cat gn-out/args.gn
  - ninja -C gn-out
  - gn-out/hello
